railwayapp/starters

package.json

Adds the open command to the package json

Add Open to Package.json

---

elixir/with-cowboy/.formatter.exs
elixir/with-cowboy/.gitignore
elixir/with-cowboy/README.md
elixir/with-cowboy/config/config.exs
elixir/with-cowboy/lib/with_cowboy.ex
elixir/with-cowboy/lib/with_cowboy/application.ex
elixir/with-cowboy/lib/with_cowboy/endpoint.ex
elixir/with-cowboy/lib/with_cowboy/router.ex
elixir/with-cowboy/mix.exs
elixir/with-cowboy/mix.lock
elixir/with-cowboy/test/test_helper.exs
elixir/with-cowboy/test/with_cowboy_test.exs

Simple elixir app that starts a JSON server with Cowboy (no Phoenix)
This example does not connect to any database

Elixir cowboy example

---

elixir/with-phoenix/README.md

Railway Run for Elixir Deps Get

---

examples/expressjs-prisma/tsconfig.json
examples/flask/.gitignore
examples/flask/Procfile
examples/flask/README.md
examples/flask/main.py
examples/flask/requirements.txt

Python flask server setup to return simple json response from `/`. No database or plugins connected

Flask server

---

examples/expressjs/README.md

This starter does not contain Postgres and this commit removes Postgres from the README as well

Fix README.md

---

examples/discordjs/README.md
examples/expressjs/README.md

Following up #57, notes had to be updated too. I've changed both Express.js and Discord.js starter notes to reflect what they do.

fix: starter notes

---

examples/starlette/.gitignore
examples/starlette/Dockerfile
examples/starlette/README.md
examples/starlette/app/main.py

Example starter for [Starlette](https://www.starlette.io/). Using docker.

feat: add example for starlette.io

---

examples/shiori/README.md

This PR adds a [Shiori](https://github.com/go-shiori/shiori) starter.
[Starter code](https://github.com/railwayapp-starters/shiori)

add shiori starter

---

examples/nocodb/README.md

This PR adds a [NocoDB](https://www.nocodb.com/) starter.

add nocodb starter

---

examples/nextjs-prisma/package.json

Fixing a starter on Railway, updating Prisma.

Update Prisma version to work in Node 16

---

examples/openvscode-server/README.md

This PR adds the [OpenVSCode Server](https://github.com/gitpod-io/openvscode-server) starter.

Add the OpenVSCode Server starter.

---

examples/ackee/README.md
examples/blitzjs/README.md
examples/calendso/README.md
examples/code-server/README.md
examples/cusdis/README.md
examples/deno/README.md
examples/djangopy/README.md
examples/elixir-phoenix/README.md
examples/eris/README.md
examples/expressjs-postgres/README.md
examples/expressjs-prisma/README.md
examples/ghost/README.md
examples/gin/README.md
examples/hasura/README.md
examples/laravel/README.md
examples/metabase/README.md
examples/n8n/README.md
examples/next-notion-blog/README.md
examples/nextjs-prisma/README.md
examples/nocodb/README.md
examples/openvscode-server/README.md
examples/rails-blog/README.md
examples/rails-starter/README.md
examples/rust-wasm/README.md
examples/shiori/README.md
examples/strapi/README.md
examples/umami/README.md

Ensure all tags have language + DB mentioned

improve tagging with lang + db support

---

examples/fider/README.md

add fider starter

---

examples/cusdis/README.md

update cusdis btn source

---

examples/nginx/Dockerfile
examples/nginx/README.md
examples/nginx/site/index.html

Deploy a static site to Railway with NGINX

NGINX Starter

---

examples/authorizer/README.md

Add starter links for https://authorizer.dev

Add authorizer.dev starter

---

examples/python-telegram-bot/Procfile
examples/python-telegram-bot/README.md
examples/python-telegram-bot/bot.py
examples/python-telegram-bot/requirements.txt

Add python-telegram-bot

---

examples/elixir-phoenix/README.md

Fixed Elixir Starter Misaligned Deploy Button

---

examples/remix/README.md

add remix starter

---

examples/openvscode-server/Dockerfile
examples/openvscode-server/README.md
examples/openvscode-server/start.sh

Fix token for openvscode-server

---

examples/mirotalk/README.md

add mirotalk starter

---

examples/discord-py/main.py

Added the new requirement of message intents by discord.py

Add message intents to examples

---

examples/logchimp/README.md

Link to devicon PR: https://github.com/railwayapp/devicons/pull/28

feat: add logchimp starter

---

examples/discordjs/README.md

Discord recently updated the command rollout system which removed the hour-long propagation time when registering or updating commands 🎉

Remove hour wait period
