railwayapp/starters

javascript/serverless/README.md
This change clarifies the getting started section to include a step to install the pg plugin. 
Without first installing the Postgres plugin I get the following error when trying to run the project:
```shell
$ railway run node src/index.js 
Error: connect ECONNREFUSED 127.0.0.1:5432
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1128:14) {
errno: 'ECONNREFUSED',
code: 'ECONNREFUSED',
syscall: 'connect',
address: '127.0.0.1',
port: 5432
}
/Users/evanboyle/garbage/rwfork/examples/javascript/serverless/src/index.js:8
console.log(res.rows);
^
TypeError: Cannot read property 'rows' of undefined
at /Users/evanboyle/garbage/rwfork/examples/javascript/serverless/src/index.js:8:19
at PendingItem.callback (/Users/evanboyle/garbage/rwfork/examples/javascript/serverless/node_modules/pg-pool/ind …
```
=> Update serverless example readme to include db setup

examples/blitzjs/README.md
=> fix: typo in README, blitz db is deprecated in favor of blitz prisma

examples/blitzjs/package.json
Blitz does not support the `--production` flag on the `start` command. The existing `start` script works fine for production deploys and is what official Blitz examples use as well.
[Docs](https://blitzjs.com/docs/cli-start)
Error when using the flag 👇
=> remove start:production script from blitz starter

examples/code-server/README.md
This PR adds the [code-server](https://github.com/cdr/deploy-code-server) starter to the starters list.
=> add code-server starter

examples/code-server/README.md
I noticed the description had it as "code-server," but I made a couple of changes to explain what code-server is and fix the heading. Totally understand if you want to keep the current description, this is just a suggestion :)
=> change code-server title

examples/next-notion-blog/package.json, examples/next-notion-blog/yarn.lock
This PR locks the NextJS version in `next-notion-blog` to NextJS 10.x as it has issues working with NextJS v11.
=> lock nextjs version to v10.x in next-notion-blog

examples/fastapi/main.py
Made the port parameter explicitly an integer to fix the `TypeError: %d format: a number is required, not str` error
=> fix fastapi starter

examples/blitzjs/app/pages/_app.tsx, examples/blitzjs/blitz.config.ts, examples/blitzjs/package.json, examples/blitzjs/types.ts, examples/blitzjs/yarn.lock, examples/node_modules/.yarn-integrity
The current `Blitz JS`  starter doesn't work as expected because of an older version of `blitz` and the requirement of ~`14` version of `node`
=> Make starter of `Blitz JS` to work

examples/cusdis/README.md
This PR adds a [Cusdis](https://cusdis.com/) starter to the starters directory on Railway.
=> add Cusdis starter

examples/discordjs-typescript/package.json, examples/discordjs-typescript/src/index.ts, examples/discordjs-typescript/yarn.lock, examples/discordjs/package.json, examples/discordjs/src/index.js, examples/discordjs/yarn.lock
Updated both `discordjs` and `discordjs-typescript` starters to use discord.js v13, along with node v16.6.0 or above.
=> Bumped discord.js version to v13

examples/rocket/Dockerfile
This PR changes the Rocket starter to build in `--release` mode by default, and to run the outputted binary directly, instead of using `cargo run` which will run the compiler a second time.
=> Tweak how Rust Rocket starter builds and runs

examples/deno/Dockerfile, examples/deno/src/index.ts
- deno v1.7.1 to v1.14.0.
- std/http v0.85.0 to v0.107.0.
- Change from old serve function to new listenAndServe function.
=> bumpup deno v1.14.0 and std/http@0.107.0

examples/deno/Dockerfile, examples/deno/src/index.ts
**bumpup**
- deno 1.16.2
- std/http 0.114.0
**listenAndServe is Deprecated**
- see: https://github.com/denoland/deno_std/pull/1506
- Fixed to use new function "serve"
=> bumpup 1.16.2 and std/http 0.114.0

examples/telegram-bot/README.md
There is index.ts in src directory of Telegram Bot Starter not index.js so I have changed .js to .ts
https://github.com/railwayapp/starters/blob/master/examples/telegram-bot/src/index.ts
=> Change index.js to index.ts

examples/openvscode-server/Dockerfile
This PR updates the executable path for `openvscode-server` to match the upstream. There's an issue in the Discord. As an alternative, I could comment out the `ENTRYPOINT` line altogether and have it inherit from the base image, which appears to still work(ish), based on local Docker testing.
A weird issue is that the URL that it says it's listening on returns no data, but that's probably because I've never used `openvscode-server` before and quite probably misconfigured it.
=> Fix openvscode-server exec path

examples/beam/README.md, examples/umami/README.md
The button now uses the new template system and points directly to the source repo. The README also contains instructions on how to use the template.
=> update umami starter to use source repo

examples/expressjs-mongoose/Procfile, examples/expressjs-postgres/Procfile, examples/expressjs-prisma/Procfile, examples/expressjs/Procfile
No procfiles were present for express starters - causing starters to fail with the message 
`failed to launch: determine start command: when there is no default process a command is required`
=> add procfiles to express starters

examples/svelte-kit/svelte.config.js
The sveltekit config no longer needs to be explicitly told the port environment variable. Fixes #309
=> Update svelte starter

examples/rails-starter/Gemfile, examples/rails-starter/Gemfile.lock
If a ruby version other than 2.7.4 is used, there are startup errors. Matching the Gemfile versions should take care of this.
=> Matched Gemfile versions in order to fix build errors

examples/aid/README.md
The button source was pointing to the repo instead of the README.
=> fix button source for aid starter
